src/meetups/meetups.service.ts
한 사서분의 의견에 의해 참여자가 2명 이상일 경우에만 매칭 슬랙 알림을 보냅니다
=> feat: send message only when there are 2 or more attendees

src/meetups/entity/meetup-attendee.entity.ts, src/meetups/entity/meetup.entity.ts, src/rotation/entity/rotation-attendee.entity.ts, src/rotation/entity/rotation.entity.ts, src/rotation/rotations.module.ts, src/user/user.service.ts
=> fix: apply change name user -> userEntity

src/rotation/rotations.controller.ts, src/rotation/rotations.service.ts, src/user/repository/user.repository.ts, src/user/user.service.ts
프론트엔드 코드에 맞게 백엔드 코드를 수정했습니다... 잘 돌아갔으면 좋겠군요...
=> merge 7-rotation-refactoring to dev

src/rotation/repository/rotations.repository.ts, src/rotation/rotations.controller.ts, src/rotation/rotations.service.ts
* 달력 기본 조회를 모든 데이터를 가져오도록 변경
* 그 외 잡다한 실수 수정...
=> modify: change logic to work with frontend

.github/workflows/deploy-dev.yml
=> fix: change ssh-action key content

.github/workflows/deploy-dev.yml, docker-compose.yml
=> fix: container name branching depending on the environment

Dockerfile
=> fix: When using COPY with source files, the destination must be end with a /

src/rotation/rotations.controller.ts
헉... 이게 PR에 안올라갔었네요... 그런데 기능상 문제는 없을 것 같습니다...
=> modify: remove undifned initialize

src/rotation/rotations.controller.ts
GetUser를 사용하는 컨트롤러에 Guards와 Role을 추가했습니다!
=> 42 modfiy: add gurads and role

src/rotation/rotations.service.ts
주석 처리로 로테이션 신청 시 4주차 확인을 해제했습니다
=> modify: 4주차 확인 로직 삭제

src/auth/auth.controller.ts, src/auth/auth.module.ts, src/auth/auth.service.ts, src/rotation/rotations.service.ts
* 로테이션 초기화가 매달 첫 일에 시작
* 회원가입 시 자동으로 로테이션 참석
* 그 외 자잘한 버그들 수정...
=> modfiy: 로테이션 수정 및 기능 추가

src/user/repository/user.repository.ts
=> fix: correcting the reversed rankings 

src/auth/auth.controller.ts, src/main.ts, src/rotation/rotations.controller.ts, src/rotation/rotations.service.ts, src/user/user.controller.ts
=> fix: final test before deployment

src/user/entity/user.entity.ts
=> feat: temporarily change the default value of user role to Librarian

src/rotation/rotations.service.ts
=> fix: use rotationRepository when findAllRotation

.github/workflows/deploy-main.yml
=> feat: add git action script for auto deploy prod server

src/rotation/rotations.service.ts, src/user/user.service.ts
=> refactor: change return value of patch /user/activity

src/holiday/holiday.service.ts, src/rotation/utils/holiday.ts
공휴일을 연에 한 번 가져오는 동작에서 매 달 한 번씩 가져오는 과정으로 변경했습니다!
=> modify: modify fetching holiday year to month

src/rotation/dto/create-registration.dto.ts, src/rotation/dto/create-rotation.dto.ts, src/rotation/dto/find-rotation-query.dto.ts, src/rotation/dto/remove-rotation.dto.ts, src/rotation/dto/update-rotation.dto.ts, src/rotation/rotations.controller.ts
controller, dto에 swagger를 적용했습니다! 엔티티에도 해야할까요...??
=> Rotation swagger 적용

src/common/dto/error-response.dto.ts, src/user/dto/user-info.dto.ts, src/user/user.controller.ts
=> docs: write users api swagger docs

src/rotation/rotations.service.ts
=> refactor: modify select option when find today rotation

src/rotation/rotations.service.ts
=> hotfix: fix rotation bug - attendLimit object to array

README.md
=> docs: add link describing changes of API and DB

src/rotation/pipe/month-validation.pipe.ts, src/rotation/rotations.controller.ts, src/rotation/rotations.service.ts
/rotations 라우트의 GET 메소드가 이제 parameter로 year와 month를 받습니다. 요청 형식은 아래와 같습니다.
/rotations?year=2024&month=3
=> change: change /rotations GET controller to use parameter

src/rotation/dto/find-all-rotation.dto.ts, src/rotation/dto/find-registration.dto.ts, src/rotation/dto/find-today-rotation.dto.ts, src/rotation/rotations.controller.ts, src/rotation/rotations.service.ts
기존에 partial entitiy로 처리했던 반환값을 특정한 dto를 통해 반환되도록 수정했습니다.
=> change: change partial entities to specific dtos

docker-compose.yml, src/app.module.ts, src/auth/auth.service.ts, src/auth/guard/jwt.guard.ts, src/auth/strategy/jwt.strategy.ts, src/batch/batch.service.ts, src/common/enum/error-message.enum.ts, src/common/exception-filter/service.exception-filter.ts, src/common/exception-filter/unknown.exception-filter.ts, src/common/exception/service.exception.ts, src/common/exception/unknown.exception.ts, src/common/interceptor/log.interceptor.ts, src/holiday/holiday.service.ts, src/holiday/repository/holiday.repository.ts, src/meetups/meetup.events-handler.ts, src/meetups/meetups.service.ts, src/middleware/google.middleware.ts, src/rotation/rotations.service.ts, src/user/repository/user.repository.ts, src/user/user.controller.ts, src/user/user.service.ts
=> feat: exception filter and logging

src/rotation/rotations.controller.ts, src/rotation/rotations.service.ts
타입 에러가 났던 부분을 수정했습니다.
제가 잘못 머지한 부분이 있었습니다..........
=> hotfix: fix type error

.github/workflows/deploy-dev.yml, .github/workflows/deploy-main.yml, docker-compose.yml
AWS Cloudwatch 옵션과 관련된 env를 추가합니다
=> build: add new env related with AWS Cloudwatch

src/rotation/rotations.service.ts
- 집현전 회의 안건에 따라 사서 로테이션을 월, 수, 금에만 배정하도록 변경합니다.
=> Modify: change rotation schedule
